/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { SudoSOSClient } from './SudoSOSClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AcceptTosRequest } from './models/AcceptTosRequest';
export type { ActionResponse } from './models/ActionResponse';
export type { AuthenticationEanRequest } from './models/AuthenticationEanRequest';
export type { AuthenticationKeyRequest } from './models/AuthenticationKeyRequest';
export type { AuthenticationLDAPRequest } from './models/AuthenticationLDAPRequest';
export type { AuthenticationLocalRequest } from './models/AuthenticationLocalRequest';
export type { AuthenticationMockRequest } from './models/AuthenticationMockRequest';
export type { AuthenticationNfcRequest } from './models/AuthenticationNfcRequest';
export type { AuthenticationPinRequest } from './models/AuthenticationPinRequest';
export type { AuthenticationResetTokenRequest } from './models/AuthenticationResetTokenRequest';
export type { AuthenticationResponse } from './models/AuthenticationResponse';
export type { BalanceResponse } from './models/BalanceResponse';
export type { BannerRequest } from './models/BannerRequest';
export type { BannerResponse } from './models/BannerResponse';
export type { BaseContainerResponse } from './models/BaseContainerResponse';
export type { BaseEventAnswerResponse } from './models/BaseEventAnswerResponse';
export type { BaseEventResponse } from './models/BaseEventResponse';
export type { BaseEventShiftResponse } from './models/BaseEventShiftResponse';
export type { BaseFineHandoutEventResponse } from './models/BaseFineHandoutEventResponse';
export type { BaseInvoiceResponse } from './models/BaseInvoiceResponse';
export type { BasePayoutRequestResponse } from './models/BasePayoutRequestResponse';
export type { BasePointOfSaleResponse } from './models/BasePointOfSaleResponse';
export type { BaseProductResponse } from './models/BaseProductResponse';
export type { BaseResponse } from './models/BaseResponse';
export type { BaseTransactionResponse } from './models/BaseTransactionResponse';
export type { BaseUserResponse } from './models/BaseUserResponse';
export type { BaseVatGroupResponse } from './models/BaseVatGroupResponse';
export type { BoilerPayoutRequestResponse } from './models/BoilerPayoutRequestResponse';
export type { ContainerResponse } from './models/ContainerResponse';
export type { ContainerWithProductsResponse } from './models/ContainerWithProductsResponse';
export type { CreateContainerRequest } from './models/CreateContainerRequest';
export type { CreateEventRequest } from './models/CreateEventRequest';
export type { CreateInvoiceRequest } from './models/CreateInvoiceRequest';
export type { CreatePointOfSaleRequest } from './models/CreatePointOfSaleRequest';
export type { CreateProductRequest } from './models/CreateProductRequest';
export type { CreateShiftRequest } from './models/CreateShiftRequest';
export type { CreateUserRequest } from './models/CreateUserRequest';
export type { Dinero } from './models/Dinero';
export type { DineroObject } from './models/DineroObject';
export type { DineroObjectRequest } from './models/DineroObjectRequest';
export type { DineroObjectResponse } from './models/DineroObjectResponse';
export type { EntityResponse } from './models/EntityResponse';
export type { EventAnswerAssignmentRequest } from './models/EventAnswerAssignmentRequest';
export type { EventAnswerAvailabilityRequest } from './models/EventAnswerAvailabilityRequest';
export type { EventInShiftResponse } from './models/EventInShiftResponse';
export type { EventPlanningSelectedCount } from './models/EventPlanningSelectedCount';
export type { EventResponse } from './models/EventResponse';
export type { EventShiftResponse } from './models/EventShiftResponse';
export type { FileRequest } from './models/FileRequest';
export type { FileUpload } from './models/FileUpload';
export { FinancialMutationResponse } from './models/FinancialMutationResponse';
export type { FineHandoutEventResponse } from './models/FineHandoutEventResponse';
export type { FineResponse } from './models/FineResponse';
export type { GEWISAuthenticationPinRequest } from './models/GEWISAuthenticationPinRequest';
export type { GewisUserResponse } from './models/GewisUserResponse';
export type { GewiswebAuthenticationRequest } from './models/GewiswebAuthenticationRequest';
export type { HandoutFinesRequest } from './models/HandoutFinesRequest';
export type { InvoiceEntryRequest } from './models/InvoiceEntryRequest';
export type { InvoiceEntryResponse } from './models/InvoiceEntryResponse';
export type { InvoiceResponse } from './models/InvoiceResponse';
export type { InvoiceResponseTypes } from './models/InvoiceResponseTypes';
export { InvoiceStatusResponse } from './models/InvoiceStatusResponse';
export type { MessageResponse } from './models/MessageResponse';
export type { PaginatedBalanceResponse } from './models/PaginatedBalanceResponse';
export type { PaginatedBannerResponse } from './models/PaginatedBannerResponse';
export type { PaginatedBaseEventResponse } from './models/PaginatedBaseEventResponse';
export type { PaginatedBasePayoutRequestResponse } from './models/PaginatedBasePayoutRequestResponse';
export type { PaginatedBaseTransactionResponse } from './models/PaginatedBaseTransactionResponse';
export type { PaginatedContainerResponse } from './models/PaginatedContainerResponse';
export type { PaginatedContainerWithProductResponse } from './models/PaginatedContainerWithProductResponse';
export type { PaginatedEventShiftResponse } from './models/PaginatedEventShiftResponse';
export type { PaginatedFinancialMutationResponse } from './models/PaginatedFinancialMutationResponse';
export type { PaginatedFineHandoutEventResponse } from './models/PaginatedFineHandoutEventResponse';
export type { PaginatedInvoiceResponse } from './models/PaginatedInvoiceResponse';
export type { PaginatedPointOfSaleResponse } from './models/PaginatedPointOfSaleResponse';
export type { PaginatedProductCategoryResponse } from './models/PaginatedProductCategoryResponse';
export type { PaginatedProductResponse } from './models/PaginatedProductResponse';
export type { PaginatedTransferResponse } from './models/PaginatedTransferResponse';
export type { PaginatedUserResponse } from './models/PaginatedUserResponse';
export type { PaginatedVatGroupResponse } from './models/PaginatedVatGroupResponse';
export type { PaginatedVoucherGroupResponse } from './models/PaginatedVoucherGroupResponse';
export type { PaginationResult } from './models/PaginationResult';
export type { PayoutRequestRequest } from './models/PayoutRequestRequest';
export type { PayoutRequestResponse } from './models/PayoutRequestResponse';
export { PayoutRequestStatusRequest } from './models/PayoutRequestStatusRequest';
export type { PayoutRequestStatusResponse } from './models/PayoutRequestStatusResponse';
export type { PointOfSaleResponse } from './models/PointOfSaleResponse';
export type { PointOfSaleWithContainersResponse } from './models/PointOfSaleWithContainersResponse';
export type { ProductCategoryRequest } from './models/ProductCategoryRequest';
export type { ProductCategoryResponse } from './models/ProductCategoryResponse';
export type { ProductResponse } from './models/ProductResponse';
export type { RelationResponse } from './models/RelationResponse';
export type { ResetLocalRequest } from './models/ResetLocalRequest';
export type { RevisionRequest } from './models/RevisionRequest';
export type { RoleResponse } from './models/RoleResponse';
export type { SimpleFileRequest } from './models/SimpleFileRequest';
export type { SimpleFileResponse } from './models/SimpleFileResponse';
export type { StripeDepositResponse } from './models/StripeDepositResponse';
export type { StripeDepositStatusResponse } from './models/StripeDepositStatusResponse';
export type { StripePaymentIntentResponse } from './models/StripePaymentIntentResponse';
export type { StripeRequest } from './models/StripeRequest';
export type { SubTransactionRequest } from './models/SubTransactionRequest';
export type { SubTransactionResponse } from './models/SubTransactionResponse';
export type { SubTransactionRowRequest } from './models/SubTransactionRowRequest';
export type { SubTransactionRowResponse } from './models/SubTransactionRowResponse';
export type { TransactionFilterParameters } from './models/TransactionFilterParameters';
export type { TransactionReportCategoryEntryResponse } from './models/TransactionReportCategoryEntryResponse';
export type { TransactionReportDataResponse } from './models/TransactionReportDataResponse';
export type { TransactionReportEntryResponse } from './models/TransactionReportEntryResponse';
export type { TransactionReportResponse } from './models/TransactionReportResponse';
export type { TransactionReportVatEntryResponse } from './models/TransactionReportVatEntryResponse';
export type { TransactionRequest } from './models/TransactionRequest';
export type { TransactionResponse } from './models/TransactionResponse';
export type { TransferRequest } from './models/TransferRequest';
export type { TransferResponse } from './models/TransferResponse';
export type { UpdateContainerRequest } from './models/UpdateContainerRequest';
export type { UpdateEventRequest } from './models/UpdateEventRequest';
export { UpdateInvoiceRequest } from './models/UpdateInvoiceRequest';
export type { UpdateKeyResponse } from './models/UpdateKeyResponse';
export type { UpdateLocalRequest } from './models/UpdateLocalRequest';
export type { UpdateNfcRequest } from './models/UpdateNfcRequest';
export type { UpdatePinRequest } from './models/UpdatePinRequest';
export type { UpdatePointOfSaleRequest } from './models/UpdatePointOfSaleRequest';
export type { UpdateProductRequest } from './models/UpdateProductRequest';
export type { UpdateShiftRequest } from './models/UpdateShiftRequest';
export type { UpdateUserRequest } from './models/UpdateUserRequest';
export type { UpdateVatGroupRequest } from './models/UpdateVatGroupRequest';
export type { UserFineGroupResponse } from './models/UserFineGroupResponse';
export type { UserResponse } from './models/UserResponse';
export type { UserToFineResponse } from './models/UserToFineResponse';
export type { VatDeclarationResponse } from './models/VatDeclarationResponse';
export type { VatDeclarationRow } from './models/VatDeclarationRow';
export type { VatGroupRequest } from './models/VatGroupRequest';
export type { VatGroupResponse } from './models/VatGroupResponse';
export type { VoucherGroupRequest } from './models/VoucherGroupRequest';
export type { VoucherGroupResponse } from './models/VoucherGroupResponse';

export { AuthenticateService } from './services/AuthenticateService';
export { BalanceService } from './services/BalanceService';
export { BannersService } from './services/BannersService';
export { ContainersService } from './services/ContainersService';
export { DebtorsService } from './services/DebtorsService';
export { EventsService } from './services/EventsService';
export { FilesService } from './services/FilesService';
export { InvoicesService } from './services/InvoicesService';
export { PayoutRequestsService } from './services/PayoutRequestsService';
export { PointofsaleService } from './services/PointofsaleService';
export { ProductCategoriesService } from './services/ProductCategoriesService';
export { ProductsService } from './services/ProductsService';
export { RbacService } from './services/RbacService';
export { RootService } from './services/RootService';
export { StripeService } from './services/StripeService';
export { TestOperationsOfTheTestControllerService } from './services/TestOperationsOfTheTestControllerService';
export { TransactionsService } from './services/TransactionsService';
export { TransfersService } from './services/TransfersService';
export { UsersService } from './services/UsersService';
export { VatGroupsService } from './services/VatGroupsService';
export { VouchergroupsService } from './services/VouchergroupsService';
