version: 2
updates:
  - package-ecosystem: "yarn"
    directories:
      - "."
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]