version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "."
    schedule:
      interval: "weekly"
    target-branch: "develop"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 15
    groups:
      dev-npm-patch-minor:
        dependency-type: "development"
        update-types:
        - "minor"
        - "patch"
      prod-npm-patch-patch:
        dependency-type: "production"
        update-types:
        - "patch"

