version: '2'
services:
  backoffice:
    build: ../narrowcasting-backoffice
    image: abc.docker-registry.gewis.nl/nc/aurora/backoffice:latest
    restart: 'unless-stopped'
    ports:
      - '8080:80'
    networks:
      - aurora
    volumes:
      - posters:/usr/src/app/data/posters
      - audio:/usr/src/app/data/audio
  client:
    build: ../narrowcasting-client
    image: abc.docker-registry.gewis.nl/nc/aurora/client:latest
    restart: 'unless-stopped'
    networks:
      - aurora
    ports:
      - '8081:80'
    volumes:
      - posters:/usr/src/app/data/posters
      - audio:/usr/src/app/data/audio
  core:
    build: .
    image: abc.docker-registry.gewis.nl/nc/aurora/core:latest
    restart: 'unless-stopped'
    networks:
      - aurora
    volumes:
      - posters:/app/public/posters
      - audio:/app/public_copy/audio
    environment:
      - PORT=3000
      - STATIC_FILES_LOCATION=/app/public_copy # fix for issue where a Docker volume overwrites the contents of a folder instead of merging them
      # See the .env.example file in the core repository to find all environment variables

volumes:
  posters:
    driver: local
  audio:
    driver: local
networks:
  aurora:
    driver: bridge
