export enum TimeTrailRaceState {
  INITIALIZED = 'INITIALIZED',
  PLAYER_REGISTERED = 'PLAYER_REGISTERED',
  PLAYER_READY = 'PLAYER_READY',
  STARTED = 'STARTED',
  FINISHED = 'FINISHED',
  SCOREBOARD = 'SCOREBOARD',
}
