enum BeatPriorities {
  DEVELOP_EFFECTS_HANDLER_BEAT_GENERATOR = 0,
  BACKGROUND_BEAT_GENERATOR = 10,
  REAL_TIME_BEAT_DETECTOR = 20,
  CENTURION_BEAT_GENERATOR = 30,
  TIME_TRAIL_BEAT_GENERATOR = 30,
  CUSTOM_BEAT_GENERATOR = 40,
}

export default BeatPriorities;
