name: Lint and build

on:
  push:
    branches: 
    - develop
  pull_request:
    branches: 
    - develop

jobs:
  build-and-lint:
    uses: GEWIS/actions/.github/workflows/typescript-lint-and-build.yml@v0.0.1
    with:
      node-version: "20.x"
      package-manager: "yarn"
      lint: true
      format: true
      build: true
