name: Docker

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/aurora-core/Dockerfile
          push: false
