name: Semantic release

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  semantic-release:
    uses: GEWIS/actions/.github/workflows/semantic-release.yml@v0.0.2
    with:
      projects: "['.']"
      docker_registry: "abc.docker-registry.gewis.nl"
      docker_paths: "['nc/aurora/core']"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.SVC_GH_ABCNC_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.SVC_GH_ABCNC_PWD }}


